repos:

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: ^src/ansys/templates/pypkg/
    args: [
    "--line-length", "100"
    ]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    exclude: ^src/ansys/templates/pypkg/
    args: [
    "--profile", "black",
    "--force-sort-within-sections",
    "--line-length", "100",
    "--section-default", "THIRDPARTY", "hooks", "tests"
    ]

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    exclude: ^src/ansys/templates/pypkg/
    args: [
      "tests",
    ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: ^src/ansys/templates/pypkg/|^tests

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.940
  hooks:
  - id: mypy