# check spelling, codestyle
name: Publish documentation

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: setup-git-credentials
        run: |
          git config --global url.https://${{ secrets.PHX_NIGHTLY_SECRET }}@github.com/pyansys/ansys-common-variableinterop.insteadOf https://github.com/pyansys/ansys-common-variableinterop
 
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PHX_NIGHTLY_SECRET }}      

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install variableinterop, with docs extra
        run: pip install .[docs]

      - name: Build HTML
        run: |
          make -C doc html 
          # Add back in to previous line once documentation is cleaned up: SPHINXOPTS="-W"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc/build/html
          retention-days: 7

#      - name: Build PDF Documentation
#        run: |
#          sudo apt update
#          sudo apt-get install -y texlive-latex-extra latexmk
#          make -C doc latexpdf

#      - name: Upload PDF Documentation
#        uses: actions/upload-artifact@v2
#        with:
#          name: Documentation-pdf
#          path: doc/build/latex/*.pdf
#          retention-days: 7

  Deploy-Pages: 
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs 
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
