# check spelling, codestyle
name: Style checks

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install style requirements
        run: |
          pip install .[style] --disable-pip-version-check

      - name: Codespell
        run: |
          make codespell

      - name: flake8
        run: |
          make flake8
